config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :dealers
end

app/models/dealer.rb
class Dealer < ActiveRecord::Base
  validates :name, :city, presence: true
  validates :state, presence: true, length: {is: 2}
  validates :zip, presence: true, length: {within: 5..9} # this could be done better by validating length 5 OR 9

  has_many :units

  def full_address joiner = ', '
    "#{address ? address + joiner : nil}#{city}, #{state}, #{zip}"
  end

  def zip= zip
  	write_attribute(:zip, zip.gsub(/\D/, ''))
  end

  def nearby_dealers
  	Dealer.where(city: city, state: state).where.not(id: id)
  end

  def has_units?
    units.count > 0
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	validates :vin, :year, :make, :model, presence: true

	belongs_to :dealer
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_token_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController

  helper_method :get_state_options_for_select

  before_filter do
    authenticate_user! if request.format.json? || request.format.xml?
  end

  def index  
    @dealers = Dealer.order('name')
    respond_to do |format|
      format.html
      format.xml { render xml: @dealers }
      format.json { render json: @dealers }
    end
  end

  def new
    @dealer = Dealer.new
  end

  def create
    @dealer = Dealer.create(dealer_params)
    redirect_to dealers_path, notice: "Dealer #{@dealer.name} created."
  end

  def edit
    @dealer = Dealer.find(params[:id])
  end

  def update
    @dealer = Dealer.find(params[:id])
    @dealer.update(dealer_params)
    redirect_to dealers_path, notice: "Dealer #{@dealer.name} updated."
  end

  def show
    @dealer = Dealer.find(params[:id])
    respond_to do |format|
      format.html
      format.xml { render xml: @dealer }
      format.json { render json: @dealer }
    end
  end

  def destroy
    @dealer = Dealer.find(params[:id])
    @dealer.destroy
    redirect_to dealers_path, notice: "Dealer #{@dealer.name} destroyed."
  end

protected

  def get_state_options_for_select
    [
      ["Alaska", "AK"],
      ["Alabama", "AL"],
      ["Arkansas", "AR"],
      ["American Samoa", "AS"],
      ["Arizona", "AZ"],
      ["California", "CA"],
      ["Colorado", "CO"],
      ["Connecticut", "CT"],
      ["District of Columbia", "DC"],
      ["Delaware", "DE"],
      ["Florida", "FL"],
      ["Georgia", "GA"],
      ["Guam", "GU"],
      ["Hawaii", "HI"],
      ["Iowa", "IA"],
      ["Idaho", "ID"],
      ["Illinois", "IL"],
      ["Indiana", "IN"],
      ["Kansas", "KS"],
      ["Kentucky", "KY"],
      ["Louisiana", "LA"],
      ["Massachusetts", "MA"],
      ["Maryland", "MD"],
      ["Maine", "ME"],
      ["Michigan", "MI"],
      ["Minnesota", "MN"],
      ["Missouri", "MO"],
      ["Mississippi", "MS"],
      ["Montana", "MT"],
      ["North Carolina", "NC"],
      ["North Dakota", "ND"],
      ["Nebraska", "NE"],
      ["New Hampshire", "NH"],
      ["New Jersey", "NJ"],
      ["New Mexico", "NM"],
      ["Nevada", "NV"],
      ["New York", "NY"],
      ["Ohio", "OH"],
      ["Oklahoma", "OK"],
      ["Oregon", "OR"],
      ["Pennsylvania", "PA"],
      ["Puerto Rico", "PR"],
      ["Rhode Island", "RI"],
      ["South Carolina", "SC"],
      ["South Dakota", "SD"],
      ["Tennessee", "TN"],
      ["Texas", "TX"],
      ["Utah", "UT"],
      ["Virginia", "VA"],
      ["Virgin Islands", "VI"],
      ["Vermont", "VT"],
      ["Washington", "WA"],
      ["Wisconsin", "WI"],
      ["West Virginia", "WV"],
      ["Wyoming", "WY"]
    ]
  end

private

  def dealer_params
    params.require(:dealer).permit(:name, :address, :city, :state, :zip)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	acts_as_token_authentication_handler_for User, fallback_to_devise: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dealers/_form.html.erb
<%= simple_form_for @dealer do |f| %>
	<%= f.input :name, label: 'Full Name' %>
	<%= f.input :address, label: 'Address' %>
	<%= f.input :city, size: 100, label: 'City' %>
	<%= f.input :state, collection: get_state_options_for_select, prompt: 'State' %>
	<%= f.input :zip, size: 10, label: 'Zip' %>
	<%= f.button :submit, (@dealer.new_record? ? 'Create' : 'Edit') %>
<% end %>

app/views/dealers/edit.html.erb
<h1>Edit <%= @dealer.name %></h1>
<%= render partial: 'form', locals: { dealer: @dealer } %>
<%= link_to 'Back to All Dealers', dealers_path %>

app/views/dealers/index.html.erb
<h1>Dealers List</h1>
<%= link_to 'Add a New Dealer', new_dealer_path %>
<br /><br />

<table class="table table-hover" width="100%">
  <thead>
    <tr>
      <th width="30%">Dealership</th>
      <th>City</th>
      <th>State</th>
      <th>Functions</th>
    </tr>
  </thead>
  <tbody>
    <% @dealers.each do |dealer| %>
      <tr>
        <td><%= dealer.name %></td>
        <td><%= dealer.city %></td>
        <td><%= dealer.state %></td>
        <td>
          <%= link_to 'Show', dealer_path(dealer) %> |
          <%= link_to 'Edit', edit_dealer_path(dealer) %> |
          <%= link_to 'Delete', dealer_path(dealer), confirm: "Really DELETE Dealer #{dealer.name}?", method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>

app/views/dealers/new.html.erb
<h1> New Dealer </h1>
<%= render partial: 'form', locals: { dealer: @dealer } %>
<%= link_to 'Back to All Dealers', dealers_path %>

app/views/dealers/show.html.erb
<h1><%= @dealer.name %></h1>
<div>
	<span><strong>Address:</strong> <%= @dealer.address %></span>
</div>
<div>
	<span><strong>City:</strong> <%= @dealer.city %></span>
</div>
<div>
	<span><strong>State:</strong> <%= @dealer.state %></span>
</div>
<div>
	<span><strong>Zip:</strong> <%= @dealer.zip %></span>
</div>

<% if @dealer.has_units? %>
	<h2>Units</h2>
	<% @dealer.units.each do |unit| %>
		<div>
			<div>
				<span><strong>VIN:</strong> <%= unit.vin %></span>
			</div>
			<div>
				<span><strong>Year:</strong> <%= unit.year %></span>
			</div>
			<div>
				<span><strong>Make:</strong> <%= unit.make %></span>
			</div>
			<div>
				<span><strong>Model:</strong> <%= unit.model %></span>
			</div>
		</div>
	<% end %>
<% end %>


<%= link_to 'Back to All Dealers', dealers_path %>

app/views/home/index.html.erb
<h1>Welcome.</h1>
<%= link_to 'Dealers', dealers_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <li><%= link_to 'Dealers', dealers_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fpx Challenge" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fpx Challenge" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>